### ISSUE TITLE
API key

### ISSUE THREAD

**Issue by CmdrMaylee** [kemikal/vadskaviata#1]
G'day mate, and thanks again for the wonderful presentation! Dunno how important it is, maybe it was intentional, but I felt obligated to let you know that you left the API key on the repo!
You're doing lovely work, so keep at it! :+1:

**Comment by kemikal** [comment]
Haha thanks mate! 
Yes, I pushed a commit with keys just before the presentation, so everyone would get them from the repo. And then the plan was to make it private. But it took like 20 seconds and I got a message from openai that the keys had been found in a public repo and therefor deleted! hahah

I will clean it up with a placeholder and leave it here for future generations!

**Comment by CmdrMaylee** [comment]
What a robust and dare I say violently quick recognition their detection has :o Learning plenty about their setup, so thanks again!
